[application]

# Tailwind config
tailwind_input = "tailwind.css"
tailwind_output = "assets/tailwind.css"

[web.app]

# HTML title tag content
title = "pp2ot-bridge"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []


[bundle]
publisher = "zurielbm"
identifier = "com.zuriel.pp2ot-bridge"
icon = ["assets/icon.icns"]

[package.metadata.release]
# This runs the Dioxus bundler after the version is bumped but before the tag is created
pre-release-hook = ["dx", "bundle", "--release"]